name: Java CI CD Pipeline

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  checkout:
    uses: ./.github/workflows/checkoutcode.yml

  file-scan:
    needs: checkout
    uses: ./.github/workflows/trivyfs.yml
    with:
      working-directory: java-app

  build-java:
    needs: file-scan
    uses: ./.github/workflows/java.yml
    with:
      java-version: '17'
      working-directory: java-app

  docker-build:
    needs: build-java
    uses: ./.github/workflows/docker-build-tag.yml
    with:
      image-name: Venuzs/java-app
      image-tag: ${{ github.run_number }}
      context: java-app/
      working-directory: java-app/
      dockerfile-path: java-app/Dockerfile

  trivy-image-scan:
    needs: docker-build
    uses: ./.github/workflows/trivyimagescan.yml
    with:
      image-name: Venuzs/java-app
      image-tag: ${{ github.run_number }}

  dockerhub-push:
    needs: trivy-image-scan
    uses: ./.github/workflows/docker-push.yml
    with:
      image-name:  Venuzs/java-app
      image-tag: ${{ github.run_number }}
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
